metadata-retriever/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Reason_for_Inactivation__c</fullName>
        <label>MB Reason for Inactivation</label>
        <picklist>
            <picklistValues>
                <fullName>The franchise was transferred.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchised business ceased to operate.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchise agreement was terminated by the franchisor:</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchise agreement was terminated by the franchisee.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchise agreement was not renewed when it expired.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchised business was bought back by the franchisor.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchise agreement was terminated and the franchised business was acquired by the franchisor.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Stores information on dealers</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Freightliner / Daimler Trucks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fuso / Daimler Trucks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB Bus &amp; Coach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB Cars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB Trucks / Daimler Trucks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB Vans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Campaign_Objective__c</fullName>
        <label>Campaign Objective</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Frequency_Category__c</fullName>
        <label>Frequency Category</label>
        <picklist>
            <picklistValues>
                <fullName>Adhoc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tri Annual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Campaign_Member_History__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CampaignMember__c</fullName>
        <label>CampaignMember</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Change__c</fullName>
        <label>Date of Change</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaign_Member_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Member History</label>
    <nameField>
        <label>Campaign Member History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Member History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Lodgement_Date__c</fullName>
        <label>Lodgement Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

metadata-retriever/metadata/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EOC_Recipient_Type__c</fullName>
        <label>EOC Recipient Type</label>
        <picklist>
            <picklistValues>
                <fullName>150 Days Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150 Days CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60 Days Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60 Days CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>45 Days Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>45 Days CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 Days Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 Days CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15 Days Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15 Days CC</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-retriever/metadata/classes/TriggerCampaignMemberTest.cls
/*
    Type:       Test class of TriggerCampaignMember 
    Purpose:    Test class of TriggerCampaignMember 
    
    User Story: CR-000151
    Used By: 
    ---------------------------------------------------------------
    History:
    
    1. Shuang Li Created on 2014-02-25
*/
@isTest
public class TriggerCampaignMemberTest {
	private static Id accDealer_RecordTypeId = 
                Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
	public static testMethod void testTaskBeforeTrigger() {
		Campaign cp = new Campaign(
                            Name = 'Campaign4InsertCampaignSharing',
                            Type = 'Other',
                            Campaign_Objective__c = 'test',
                            Description = 'test',
                            Status = 'Planned',
                            StartDate = Date.Today(),
                            EndDate = Date.Today(),
                            Brand__c = 'smart',
                            Frequency_Category__c = 'Daily');
        
        insert cp;
        Account dealeraccount1 = new Account( Name = 'nameAccount',
                                              Email__c = 'sichao.lai@nttdata.com',
                                              RecordTypeId = accDealer_RecordTypeId,
                                              Phone = '(01) 2334 3442',
                                              Dealer_Reason_for_Inactivation__c = 'Test');
        insert dealeraccount1;
        
        Contact contact1 = new Contact ( AccountId = dealeraccount1.id,
                                         FirstName = 'lai',
                                         LastName = 'sichao',
                                         Email = 'sichao.lai@nttdata.com',
                                         EOC_Recipient_Type__c = '60 Days Primary');
        insert contact1;
        // Campaign Member Initial
        CampaignMember cm1 = new CampaignMember(CampaignId = cp.Id,
                                                Status ='Sent',
                                                Lodgement_Date__c = Date.Today(),
                                                ContactId = contact1.Id
                                                );
        Test.startTest();
        insert cm1;
        List<Campaign_Member_History__c> cmhs = [Select Action__c, Date_of_Change__c, User__r.Name From Campaign_Member_History__c Where CampaignMember__c  = :cm1.id];        
        for (Campaign_Member_History__c cmh : cmhs){
        system.assertEquals(cmh.Action__c,'Created.');
        }
        cm1.Status= 'Responded';
        cm1.Lodgement_Date__c= Date.Today().addDays(1);
        update cm1;
        delete cm1;
	}
}