metadata-retriever/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CV_Status__c</fullName>
        <description>Needs to be coded:

Status a customer can have in regards to CV. 
Prospect - is interested in CV
Customer - does have at least one CV
Service Only - does have at least one After Sales Record</description>
        <label>CV Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <label>PC Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Aftersales__c.object
<CustomObject>
    <description>Contact Portfolio: To record MBCL Aftersales record
Changed object name from &quot;Aftersales Record&quot; to &quot;Aftersales&quot;</description>
    <fields>
        <fullName>Service_Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Attribute in Data Dictionary object Aftersales is &quot;Service_Vehicle&quot;</description>
        <label>Service Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>Aftersales_Record</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Aftersales</label>
    <nameField>
        <displayFormat>SN-{000000000}</displayFormat>
        <label>Service No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aftersales</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>VIN - Displays the VIN of the vehicle linked to the contract</description>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Customer_Vehicle_Relationship__c.object
<CustomObject>
    <description>Stores information on Vehicle Relationship</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>ID of related person</inlineHelpText>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Company, Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationship</relationshipLabel>
        <relationshipName>CustomerVehicleRelationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Stores information on Vehicle (cannot be created, but specific fields can be updated)</description>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <picklist>
            <picklistValues>
                <fullName>A-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All New A-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-Class Coupe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLA-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLC-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLK-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLS-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLS Shooting Brake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FIGHTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F SERIES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB 100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB 140</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ROSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLK-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLS AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLS-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart Forfour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart Fortwo cabrio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valente</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle_Group__c</fullName>
        <label>Vehicle Group</label>
        <picklist>
            <picklistValues>
                <fullName>VAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CV</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/classes/AfterSalesHelperTest.cls
/*
    Type:       AfterSales Controller Test
    Purpose:    Test the class
    User Story: 
    ---------------------------------------------------------------
    History:

    1. Bai Bing created on 2013-08-08

*/
@isTest(seeAllData=true)
private class AfterSalesHelperTest {

    private static TestDataUtil testData = TestDataUtil.getInstance();
    static Account customer1 = testData.standardPersonAccount;
                                    
    static testMethod void myUnitTest() {
        testUscd001And002();
    }
    
    static void testUscd001And002(){
        insert customer1;
        Vehicle__c car1 = new Vehicle__c(Name='xxxxxxxx01',Class__c='C-Class Sedan');
        Vehicle__c car2 = new Vehicle__c(Name='xxxxxxxx02',Class__c='CL-Class');
        Vehicle__c car3 = new Vehicle__c(Name='xxxxxxxx03',Class__c='Valente');
        Vehicle__c car4 = new Vehicle__c(Name='xxxxxxxx04',Class__c='Fighter');
        insert car1;
        system.debug([select id ,Vehicle_Group__c from Vehicle__c where id=:car1.id]);
        Aftersales__c record1 = new Aftersales__c(Service_Vehicle__c=car1.id );
        insert record1;
        
        customer1 = [select PC_Status__c from Account where id=:customer1.id];
        
        //system.assertEquals('Service Only',customer1.PC_Status__c);
        

        insert car4;
        insert car2;
        Customer_Vehicle_Relationship__c cvr = new Customer_Vehicle_Relationship__c(Customer__c=customer1.id,Vehicle_ID__c=car2.id);
        Contract contractPC = new Contract( AccountId = customer1.Id,
                                            StartDate = Date.Today(),
                                            ContractTerm = 18,
                                            Status = 'Draft',
                                            Vehicle__c = car2.Id);

        Customer_Vehicle_Relationship__c cvr1 = new Customer_Vehicle_Relationship__c(Customer__c=customer1.id,Vehicle_ID__c=car4.id);
        Contract contractPC1 = new Contract( AccountId = customer1.Id,
                                            StartDate = Date.Today(),
                                            ContractTerm = 18,
                                            Status = 'Draft',
                                            Vehicle__c = car4.Id);
        insert cvr;
        insert contractPC;
        insert cvr1;
        insert contractPC1;

        Aftersales__c record2 = new Aftersales__c(Service_Vehicle__c=car4.id );
        Aftersales__c record3 = new Aftersales__c(Service_Vehicle__c=car2.id );
        insert record2;
        insert record3;
        customer1 = [select CV_Status__c from Account where id=:customer1.id];
        
        //system.assertEquals('Service Only',customer1.CV_Status__c);
    }
}