metadata-retriever/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Reason_for_Inactivation__c</fullName>
        <label>MB Reason for Inactivation</label>
        <picklist>
            <picklistValues>
                <fullName>The franchise was transferred.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchised business ceased to operate.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchise agreement was terminated by the franchisor:</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchise agreement was terminated by the franchisee.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchise agreement was not renewed when it expired.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchised business was bought back by the franchisor.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchise agreement was terminated and the franchised business was acquired by the franchisor.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Suburb__c</fullName>
        <label>Suburb</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Salutation to client (in personal contact or via mail) 
Used in: Page Layouts, Reports 

Modify History: March 1st
Modify By: Lio Huang
Modify Reason: Changed the values between Title and salutation, also removed the prefix &quot;Contact_&quot;
*/
Attribute in Data Dictionary object Contact is &quot;Contact_Salutation&quot;</description>
        <label>Title</label>
        <picklist>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Captain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chaplain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colonel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulate General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Countess</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estate of the Late</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Her Excellency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>His Excellency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Honourable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Justice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lady</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lieutenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lieutenant Colonel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lord</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Madam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <description>Stores information on companies</description>
        <label>Company</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Stores information on dealers</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Customer_Dealer_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Person Account, Company</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Relationships</relationshipLabel>
        <relationshipName>Dealer_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Relationships</relationshipLabel>
        <relationshipName>Customer_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Customer Dealer Relationship</label>
    <nameField>
        <displayFormat>CDR-{00000000}</displayFormat>
        <label>Customer Dealer Rel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Dealer Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata-retriever/metadata/classes/CustomerDealerRelHelperTest.cls
/*
    Type:       Test class
    Purpose:    Test the CustomerDealerRelHelper class
    User Story: 
    ---------------------------------------------------------------
    History:

    1. Justin Yu created on 2013-08-28
*/
@isTest
public with sharing class CustomerDealerRelHelperTest {
    
    @isTest
    public static void testPreventRelationshipSaving(){
        
        String companyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Company').getRecordTypeId();
        String dealerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        
        Account company = new Account(
                Name = 'Company',
                Title__c = 'Title', 
                Phone = '(01) 2345 4422', 
                Address_Line_1__c = 'addressline1', 
                Suburb__c = 'suburb',
                RecordTypeId = companyRecordTypeId
        );
        insert company;
        
        Account dealer = new Account(
            Name = 'Dealer',
            Title__c = 'Title', 
            Phone = '(01) 2345 4422', 
            Address_Line_1__c = 'addressline1', 
            Suburb__c = 'suburb',
            RecordTypeId = dealerRecordTypeId,
            Dealer_Reason_for_Inactivation__c = 'Reason1'
        );
        insert dealer;
        
        Customer_Dealer_Relationship__c noTypeRel = new Customer_Dealer_Relationship__c();
        noTypeRel.Dealer__c = dealer.Id;
        noTypeRel.Customer__c = company.Id;
        
        Customer_Dealer_Relationship__c serviceRel1 = new Customer_Dealer_Relationship__c();
        serviceRel1.Dealer__c = dealer.Id;
        serviceRel1.Customer__c = company.Id;
        serviceRel1.Type__c = 'Service';
        
        Customer_Dealer_Relationship__c serviceRel2 = new Customer_Dealer_Relationship__c();
        serviceRel2.Dealer__c = dealer.Id;
        serviceRel2.Customer__c = company.Id;
        serviceRel2.Type__c = 'Service';
        
        Customer_Dealer_Relationship__c customerRel = new Customer_Dealer_Relationship__c();
        customerRel.Dealer__c = dealer.Id;
        customerRel.Customer__c = company.Id;
        customerRel.Type__c = 'Customer';

        Customer_Dealer_Relationship__c prospectRel = new Customer_Dealer_Relationship__c();
        prospectRel.Dealer__c = dealer.Id;
        prospectRel.Customer__c = company.Id;
        prospectRel.Type__c = 'Prospect';
        
        Customer_Dealer_Relationship__c prospectRel2 = new Customer_Dealer_Relationship__c();
        prospectRel2.Dealer__c = dealer.Id;
        prospectRel2.Customer__c = company.Id;
        prospectRel2.Type__c = 'Prospect';
        
        
        insert prospectRel;
        try{
            insert noTypeRel;
        }catch(DMLException e){
            system.assertEquals('The imported relationship has no type',e.getDmlMessage(0));
        }

        insert serviceRel1;
        List<Customer_Dealer_Relationship__c> customer1 = [select Dealer__c, Customer__c, Type__c from Customer_Dealer_Relationship__c where Dealer__c = :dealer.Id and Customer__c = :company.Id order by id];
        /*System.assertEquals(customer1.size(),1);
        System.assertEquals(customer1.get(0).Type__c,'Service');*/
        
        insert prospectRel2;
        List<Customer_Dealer_Relationship__c> customer4 = [select Dealer__c, Customer__c, Type__c from Customer_Dealer_Relationship__c where Dealer__c = :dealer.Id and Customer__c = :company.Id order by id];
        /*System.assertEquals(customer4.size(),1);
        System.assertEquals(customer4.get(0).Type__c,'Service');*/

        insert customerRel;
        List<Customer_Dealer_Relationship__c> customer3 = [select id ,Dealer__c, Customer__c, Type__c from Customer_Dealer_Relationship__c where Dealer__c = :dealer.Id and Customer__c = :company.Id order by id];
        /*System.assertEquals(customer3.size(),1);
        System.assertEquals(customer3.get(0).Type__c,'Customer');*/

        insert serviceRel2;
        List<Customer_Dealer_Relationship__c> customer2 = [select id ,Dealer__c, Customer__c, Type__c from Customer_Dealer_Relationship__c where Dealer__c = :dealer.Id and Customer__c = :company.Id order by id];
        /*System.assertEquals(customer2.size(),1);
        System.assertEquals(customer2.get(0).Type__c,'Customer');*/
    }
}