metadata-retriever/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CV_Status__c</fullName>
        <description>Needs to be coded:

Status a customer can have in regards to CV. 
Prospect - is interested in CV
Customer - does have at least one CV
Service Only - does have at least one After Sales Record</description>
        <label>CV Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_Reason_for_Inactivation__c</fullName>
        <label>MB Reason for Inactivation</label>
        <picklist>
            <picklistValues>
                <fullName>The franchise was transferred.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchised business ceased to operate.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchise agreement was terminated by the franchisor:</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchise agreement was terminated by the franchisee.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchise agreement was not renewed when it expired.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchised business was bought back by the franchisor.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The franchise agreement was terminated and the franchised business was acquired by the franchisor.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fleet__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fleet</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inactivation_Date__c</fullName>
        <label>MB Inactivation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <label>PC Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VAN_Status__c</fullName>
        <label>VAN Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <description>Stores information on companies</description>
        <label>Company</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Stores information on dealers</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EOC_Recipient_Type__c</fullName>
        <label>EOC Recipient Type</label>
        <picklist>
            <picklistValues>
                <fullName>150 Days Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150 Days CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60 Days Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60 Days CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>45 Days Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>45 Days CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 Days Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 Days CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15 Days Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15 Days CC</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Dealer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the dealer name who is involved in this contract</description>
        <label>Dealer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <filterItems>
                <field>Account.Dealer_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (Dealer Name)</relationshipLabel>
        <relationshipName>Contracts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fleet__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Fleet - indicates whether the related compay is a fleet customer or not</description>
        <inlineHelpText>Fleet - indicates whether the related compay is a fleet customer or not</inlineHelpText>
        <label>Fleet</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>VIN - Displays the VIN of the vehicle linked to the contract</description>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X150_Days_Before_EOC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>/*
Created By Polaris Yu 2013-8-22
Function: This field will be updated by workflow 150 days before the contract end date to trigger the auto creating leads function and sending email function
Used By: 
*/</description>
        <label>*150 Days Before EOC</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Fleet__c.object
<CustomObject>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Fleet</relationshipLabel>
        <relationshipName>Fleet</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fleet</label>
    <nameField>
        <label>Fleet Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Stores information on Vehicle (cannot be created, but specific fields can be updated)</description>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <picklist>
            <picklistValues>
                <fullName>A-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All New A-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-Class Coupe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLA-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLC-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLK-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLS-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLS Shooting Brake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FIGHTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F SERIES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB 100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB 140</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ROSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLK-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLS AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLS-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart Forfour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart Fortwo cabrio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valente</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/classes/ContractHelperTest.cls
/*
    Type:       Test class of ContractHelper 
    Purpose:    Test class of ContractHelper 
    
    User Story: US-CD-001
    Used By: 
    ---------------------------------------------------------------
    History:
    
    12-Aug-2013 Chaos (NTTData)  Created
    26-Aug-2013 Polaris Yu (BreakingPoint) Updated
*/     
@isTest(seeAlldata=true)
public class ContractHelperTest {

    private static TestDataUtil testData = TestDataUtil.getInstance();

    public static testMethod void testUpdateWhenCreateCCR() {
        
        Account normalAcc = testData.standardPersonAccount;
        insert normalAcc;
        Account accountPC = normalAcc.clone();
        accountPC.LastName = 'lastnamePC';
        Account accountCV = normalAcc.clone();
        accountCV.LastName = 'lastnameCV';
        insert accountPC;
        insert accountCV;
        
        Vehicle__c carPC = new Vehicle__c( Name='NamePC',
                                            Class__c = 'C-Class Sedan'
                                            );
        Vehicle__c carCV = new Vehicle__c( Name='NameCV',
                                            Class__c = 'Columbia'
                                            );
        Vehicle__c carVAN = new Vehicle__c( Name='NameCV',
                                            Class__c = 'Valente'
                                            );
        insert carPC;
        insert carCV;
        insert carVAN;

        // Branch 1 (Vehicle : PC , PC_Status : '') 
        Contract contractPC = new Contract( StartDate = Date.Today(),
                                            ContractTerm = 18,
                                            AccountId = accountPC.Id,
                                            Vehicle__c = carPC.Id);
        insert contractPC;
        
        // Get the latest Account info
        accountPC = [select Id, PC_Status__c, CV_Status__c, Status__c from Account where Id = :accountPC.id];
        
        // Validate
        
        /*System.assertEquals(accountPC.PC_Status__c, 'Customer');
        System.assertEquals(accountPC.CV_Status__c, 'Prospect');*/
      
        // Branch 2 (Vehicle : PC , PC_Status : Customer) 
        Contract customerContractPC = new Contract( StartDate = Date.Today(),
                                            ContractTerm = 18,
                                            AccountId = accountPC.Id,
                                            Vehicle__c = carPC.Id);
        insert customerContractPC;
        
        // Get the latest Account info
        accountPC = [select Id, PC_Status__c, CV_Status__c, Status__c from Account where Id = :accountPC.id];
        
        /*System.assertEquals(accountPC.PC_Status__c, 'Customer');
        System.assertEquals(accountPC.CV_Status__c, 'Prospect');*/
      
        // Branch 3 (Vehicle : CV , CV_Status : '') 
        Contract contractCV = new Contract( StartDate = Date.Today(),
                                            ContractTerm = 18,
                                            AccountId = accountCV.Id,
                                            Vehicle__c = carCV.Id);
        insert contractCV;
        
        // Get the latest Account info
        accountCV = [select Id, PC_Status__c, CV_Status__c, Status__c from Account where Id = :accountCV.id];
        
        /*System.assertEquals(accountCV.CV_Status__c, 'Customer');
        System.assertEquals(accountCV.PC_Status__c, 'Prospect');*/
      
        // Branch 4 (Vehicle : CV , CV_Status : Customer) 
        Contract customerContractCV = new Contract( StartDate = Date.Today(),
                                            ContractTerm = 18,
                                            AccountId = accountCV.Id,
                                            Vehicle__c = carCV.Id);
        insert customerContractCV;
        
        // Get the latest Account info
        accountCV = [select Id, PC_Status__c, CV_Status__c, Status__c from Account where Id = :accountCV.id];
        
        /*System.assertEquals(accountCV.CV_Status__c, 'Customer');
        System.assertEquals(accountCV.PC_Status__c, 'Prospect');*/

        // Branch 5 (Vehicle : VAN , VAN_Status : Customer) 
        Contract customerContractVAN = new Contract( StartDate = Date.Today(),
                                            ContractTerm = 18,
                                            AccountId = accountCV.Id,
                                            Vehicle__c = carVAN.Id);
        insert customerContractVAN;
        
        // Get the latest Account info
        accountCV = [select Id, VAN_Status__c,PC_Status__c, CV_Status__c, Status__c from Account where Id = :accountCV.id];
        
        //System.assertEquals(accountCV.VAN_Status__c, 'Customer');
    }

    // Added by Polaris Yu 2013-8-26; Test codes for autoCreateLeads 
    //    method in ContractHelper.cls 
    public static testMethod void testAutoCreateLeads(){
        // Create a Person Account, a company account and a Dealer Account
        List<Account> accInsertList = new List<Account>();
        Account personAcc = testData.standardPersonAccount;
        accInsertList.add(personAcc);

        Id companyRTId
            = Schema.SObjectType.Account.getRecordTypeInfosByName()
              .get('Company').getRecordTypeId();
        Account companyAcc = new Account(Status__c = 'Customer'
                                         , Name = 'TestCompany' + date.Today()
                                         , RecordTypeId = companyRTId
                                         , Phone ='(01) 8677 0993');
        accInsertList.add(companyAcc);

        Id dealerRTId
            = Schema.SObjectType.Account.getRecordTypeInfosByName()
              .get('Dealer').getRecordTypeId();
        Account dealer1 = new Account(Status__c = 'Customer'
                                     , Name = 'TestDealer' + date.Today()
                                     , RecordTypeId = dealerRTId
                                     , Phone ='(01) 8677 0993'
                                     , Inactivation_Date__c = date.Today().addDays(100)
                                     , Dealer_Active__c =true
                                     , Dealer_Reason_for_Inactivation__c = 'Test Record');
        accInsertList.add(dealer1);
        Account dealer2 = new Account(Status__c = 'Customer'
                                     , Name = 'TestDealer2' + date.Today()
                                     , RecordTypeId = dealerRTId
                                     , Phone ='(01) 8677 0993'
                                     , Dealer_Active__c =true
                                     , Inactivation_Date__c = date.Today().addDays(100)
                                     , Dealer_Reason_for_Inactivation__c = 'Test Record');
        accInsertList.add(dealer2);

        try{
            insert accInsertList;
        }
        catch(DMLException e){
            System.debug('Debug Output ======> {Error: ' + e + '}');
        }

        List<Contact> cnttList = new List<Contact>();
        // Create a '150 Days Primary' dealer contact and a '150 Days CC' dealer
        //    contact on the dealer account
        Contact primCntt1 = new Contact(AccountId = dealer1.Id
                                       , LastName = 'Test'
                                       , FirstName = 'Primary1'
                                       , Email = 'test@test.com'
                                       , EOC_Recipient_Type__c = '150 Days Primary');
        cnttList.add(primCntt1);
        Contact ccCntt1 = new Contact(AccountId = dealer1.Id
                                     , LastName = 'Test'
                                     , FirstName = 'CC1'
                                     , Email = 'test@test.com'
                                     , EOC_Recipient_Type__c = '150 Days CC');
        cnttList.add(ccCntt1);
        Contact ccCntt2 = new Contact(AccountId = dealer2.Id
                                      , LastName = 'Test'
                                      , FirstName = 'CC2'
                                      , Email = 'test@test.com'
                                      , EOC_Recipient_Type__c = '150 Days CC');
        cnttList.add(ccCntt2);
        Contact primCntt2 = new Contact(AccountId = dealer2.Id
                                        , LastName = 'Test'
                                        , FirstName = 'Primary2'
                                        , Email = 'test@test.com'
                                        , EOC_Recipient_Type__c = '150 Days Primary');
        cnttList.add(primCntt2);
        try{
            insert cnttList;
        }
        catch(DMLException e){
            System.debug('Debug Output ======> {Error: ' + e + '}');
        }

        List<Contract> cntrctList = new List<Contract>();
        // Construct a non-fleet contract
        Contract finCntrct1 = new Contract(Status = 'Draft'
                                          , StartDate = date.Today().addDays(30)
                                          , ContractTerm = 3
                                          , AccountId = personAcc.Id
                                          , Dealer_Name__c = dealer1.Id);
        cntrctList.add(finCntrct1);
        Contract finCntrct2 = new Contract(Status = 'Draft'
                                          , StartDate = date.Today().addDays(30)
                                          , ContractTerm = 3
                                          , AccountId = personAcc.Id
                                          , Dealer_Name__c = dealer2.Id);
        cntrctList.add(finCntrct2);

        // Construct a fleet contract
        Contract fltCntrct = new Contract(Status = 'Draft'
                                          , StartDate = date.Today().addDays(30)
                                          , ContractTerm = 3
                                          , AccountId = companyAcc.Id
                                          , Dealer_Name__c = dealer1.Id
                                          , Fleet__c = true);
        cntrctList.add(fltCntrct);

        // Insert the contracts
        try{
            insert cntrctList;
        }
        catch(DMLException e){
            System.debug('Debug Output ======> {Error: ' + e + '}');
        }

        for(Contract cntrct : cntrctList){
            cntrct.X150_Days_Before_EOC__c = true;
        }

        // Update the field '*150 Days Before EOC' to TRUE
        try{
            update cntrctList;
        }
        catch(DMLException e){
            System.debug('Debug Output ======> {Error: ' + e + '}'); 
        }
    }
    // End of added part, Polaris Yu 2013-8-26
}