metadata-retriever/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CV_No_Brand_Purchases__c</fullName>
        <description>PC &amp; CV No. Brand Purchases: These fields display the amount of purchases for MB PC  or CV the customer has made during the time frame first purchase and today. (frequency of calculation needs to be defined)</description>
        <label>CV No. Brand Purchases</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CV_Status__c</fullName>
        <description>Needs to be coded:

Status a customer can have in regards to CV. 
Prospect - is interested in CV
Customer - does have at least one CV
Service Only - does have at least one After Sales Record</description>
        <label>CV Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CV_Tenure__c</fullName>
        <description>PC &amp; CV tenure: these fields display the endurance the customer stays with MB PC  or CV. Calculation is based on the first purchase date of MB PC  or CV (information available on the customer vehicle relationship) (frequency of calculation needs to be defined)</description>
        <label>CV Tenure</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Only for person account. Look up to customer company as the contact.</description>
        <label>Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Company</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>Concatenated information - Display Name. The field &quot;Display Name&quot; shall display the correct salutation,  probably used to address the customer correctly, as per definition:
a) if the surname of Customer and Partner is equal then &lt;Title Customer&gt; and &lt;Title Partner&gt; &lt;Surname Customer&gt; (e.g. Mr and Ms Jones)
b) If the surname  is unequal the &lt;Title Customer&gt;  &lt;First Name Surname Customer&gt; and &lt;Title Partner&gt;  &lt;First Name Surname Partner&gt;  (e.g. Mr Mark Jones and Ms Amie Davison)
c.) if no partner information available &lt;Customer Title&gt; &lt; First Name&gt; &lt;Surname&gt;</description>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Last_Modified_By__c</fullName>
        <description>Contact Info Status 
- Opt In Email (BOOLEAN) (BOOLEAN) default unchecked (new field) 
- Last Modified By (STRING)</description>
        <label>Email Last Modified By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Last_Modified_Date__c</fullName>
        <description>Contact Info Status 
- Opt In Email (BOOLEAN) (BOOLEAN) default unchecked (new field) 
- Last Modified By (STRING)</description>
        <label>Email Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FS_Email_Last_Modified_By__c</fullName>
        <label>FS Email Last Modified By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FS_Email_Last_Modified_Date__c</fullName>
        <label>FS Email Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FS_Hardcopy_Last_Modified_By__c</fullName>
        <label>FS Mail Last Modified By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FS_Hardcopy_Last_Modified_Date__c</fullName>
        <label>FS Mail Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FS_Opt_In_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FS Opt In Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FS_Opt_In_Hardcopy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FS Opt In Mail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FS_Opt_In_Phone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FS Opt In Phone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FS_Phone_Last_Modified_By__c</fullName>
        <label>FS Phone Last Modified By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FS_Phone_Last_Modified_Date__c</fullName>
        <label>FS Phone Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Hardcopy_Last_Modified_By__c</fullName>
        <description>The fields &quot;Last Updated By&quot; and &quot;Last Updated Date&quot; for each OptIn option are to be read only. They will be updated either via interface data load or the system will set the date and the user name into respective fields. The user name will be not be a lookup onto a really existing user as done for similar fields.</description>
        <label>Mail Last Modified By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hardcopy_Last_Modified_Date__c</fullName>
        <description>The fields &quot;Last Updated By&quot; and &quot;Last Updated Date&quot; for each OptIn option are to be read only. They will be updated either via interface data load or the system will set the date and the user name into respective fields. The user name will be not be a lookup onto a really existing user as done for similar fields.</description>
        <label>Mail Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opt_In_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PersonHasOptedInOfEmail, per default un checked</description>
        <label>Opt In Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opt_In_Hardcopy__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PersonHasOptedOutOfHardCopy</description>
        <label>Opt In Mail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opt_In_Phone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PersonHasOptedInOfPhone</description>
        <label>Opt In Phone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_No_Brand_Purchases__c</fullName>
        <description>PC &amp; CV No. Brand Purchases: These fields display the amount of purchases for MB PC  or CV the customer has made during the time frame first purchase and today. (frequency of calculation needs to be defined)</description>
        <label>PC No. Brand Purchases</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <label>PC Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PC_Tenure__c</fullName>
        <description>PC &amp; CV tenure: these fields display the endurance the customer stays with MB PC  or CV. Calculation is based on the first purchase date of MB PC  or CV (information available on the customer vehicle relationship) (frequency of calculation needs to be defined)</description>
        <label>PC Tenure</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Partner_First_Name__c</fullName>
        <label>Partner First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Surname__c</fullName>
        <label>Partner Surname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Title__c</fullName>
        <description>Partner Title - Should be the same values as used for the customer title</description>
        <label>Partner Title</label>
        <picklist>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mrs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Captain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chaplain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colonel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulate General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Countess</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estate of the Late</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Her Excellency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>His Excellency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Honourable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Justice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lady</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lieutenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lieutenant Colonel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lord</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Madam</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone_Last_Modified_By__c</fullName>
        <description>The fields &quot;Last Updated By&quot; and &quot;Last Updated Date&quot; for each OptIn option are to be read only. They will be updated either via interface data load or the system will set the date and the user name into respective fields. The user name will be not be a lookup onto a really existing user as done for similar fields.</description>
        <label>Phone Last Modified By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Last_Modified_Date__c</fullName>
        <description>The fields &quot;Last Updated By&quot; and &quot;Last Updated Date&quot; for each OptIn option are to be read only. They will be updated either via interface data load or the system will set the date and the user name into respective fields. The user name will be not be a lookup onto a really existing user as done for similar fields.</description>
        <label>Phone Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Suffix__c</fullName>
        <description>Suffix - shall be displayed together with Title Fist Name &amp; Surname</description>
        <label>Suffix</label>
        <picklist>
            <picklistValues>
                <fullName>jr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>III</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VAN_No_Brand_Purchases__c</fullName>
        <label>VAN No. Brand Purchases</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VAN_Status__c</fullName>
        <label>VAN Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VAN_Tenure__c</fullName>
        <label>VAN Tenure</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <description>Stores information on companies</description>
        <label>Company</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Stores information on dealers</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/classes/AccountHelper.cls
/*
    Type:       Utility for Account
    Purpose:    For user story process unit 
    User Story: US_AU-CD-001, US_AU-CD-002, US_AU-CD-001.6, US_AU-DD-004
    Used By:    AccountTriggerBeforeInsertOrUpdate
    ---------------------------------------------------------------
    History:
        1. Bing Bai Created on 2013-08-05
        2. Stanley updated on 2013-08-07
        3. Justin Yu modified on 2013-08-09
        4. Stanley Yang updated on 2013-08-30
        5. Sinow updated on 2013-09-26     delete Dealer locators   US_AU-DD-004
        6. Shuang Li updated on 2014-02-20     CR-000213
*/
public with sharing class AccountHelper {

    private static final String ONE_SPACE = ' ';
    
    public static final Set<Id> RECORD_TYPE_SET = new Set<Id>{
        Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(),
        Schema.SObjectType.Account.getRecordTypeInfosByName().get('Company').getRecordTypeId()
    };
        
    //US-CD-001 #7. update field "Display Name"
    public static Account updateDisplayName(Account acc){
        
        if (String.isblank(acc.Partner_Surname__c)) {
            //if no partner information available than <Customer Title> < First Name> <Surname> <Suffix>
            acc.Display_Name__c = 
                (String.isblank(acc.Salutation)?'': acc.Salutation + ONE_SPACE) + 
                (String.isblank(acc.FirstName)?'': acc.FirstName + ONE_SPACE) + 
                (String.isblank(acc.LastName)?'': acc.LastName + ONE_SPACE) + 
                (String.isblank(acc.Suffix__c)?'': acc.Suffix__c);
        }else{
            //if the surname of Customer and Partner is equal then <Title Customer> and <Title Partner> <Surname Customer>
            if (acc.LastName == acc.Partner_Surname__c){
                acc.Display_Name__c = 
                    (String.isblank(acc.Salutation)? '' : acc.Salutation) + 
                    ' and ' + 
                    (String.isblank(acc.Partner_Title__c)?'': acc.Partner_Title__c) + ONE_SPACE + 
                    (String.isblank(acc.LastName)?'': acc.LastName);
            }else{
               //If the surname is unequal the <Title Customer> <First Name Surname Customer> and <Title Partner> <First Name Surname Partner>
                acc.Display_Name__c = (String.isblank(acc.Salutation)?'': acc.Salutation + ONE_SPACE) + 
                                      (String.isblank(acc.FirstName)?'': acc.FirstName + ONE_SPACE) + 
                                      (String.isblank(acc.LastName)?'': acc.LastName) + ' and ' +
                                      (String.isblank(acc.Partner_Title__c)?'': acc.Partner_Title__c + ONE_SPACE) +
                                      (String.isblank(acc.Partner_First_Name__c)?'': acc.Partner_First_Name__c + ONE_SPACE) +
                                      (String.isblank(acc.Partner_Surname__c)?'': acc.Partner_Surname__c);
            }
        }
        return acc;
    }
    
    //US-CD-001, US-CD-002 Get pc status and cv status by customerIds
    public static Map<id,Account> getCustomerInfos(set<Id> ids){
        return new Map<id,Account>([
               select id,
                       PC_Status__c,
                       CV_Status__c,
                       PC_Tenure__c,
                       CV_Tenure__c,
                       PC_No_Brand_Purchases__c,
                       CV_No_Brand_Purchases__c,
                       VAN_Status__c,
                       VAN_Tenure__c,
                       VAN_No_Brand_Purchases__c
                from Account
                where Id in :ids]);
    }

    //US-CD-001, US-CD-002 set field default value when object created
    public static Account setDefaultValue(Account acc){
        if (RECORD_TYPE_SET.contains(acc.RecordTypeId)){
            acc.PC_Status__c = 'Prospect';
            acc.CV_Status__c = 'Prospect';
            acc.VAN_Status__c = 'Prospect';
        }
        return acc;
    }
     
    // US_AU-CD-004: cancel the primary contact.
    public static void cancelPrimaryContact(Set<String> newCompanyIds, Set<String> personIds){
        
        Account[] cancelPrimaryAccounts = [select Primary__pc from Account 
                                           where Company__c in :newCompanyIds 
                                           and Primary__pc = true
                                           and Id not in :personIds];
        if(cancelPrimaryAccounts.size() > 0){
            for(Account item : cancelPrimaryAccounts){
                item.Primary__pc = false;
            }
            update cancelPrimaryAccounts;
        }
    }
    
    // US_AU-CD-004: flag the primary contact.
    public static void flagPrimaryContact(Set<String> companyIds){
        
        Map<String, Account> primaryContacts = new Map<String, Account>();
        Map<String, List<Account>> contacts = new Map<String, List<Account>>();
        
        for(Account item : [select Primary__pc, Company__c from Account where Company__c in :companyIds order by CreatedDate desc]){
            if(contacts.containsKey(item.Company__c)){
                contacts.get(item.Company__c).add(item);
            }
            else{
                contacts.put(item.Company__c, new List<Account>{item});
            }
        }

        for(String companyId : companyIds){
            List<Account> cons = contacts.get(companyId);
            if(cons != null && cons.size() > 0){
                cons[0].Primary__pc = true;
                primaryContacts.put(cons[0].Id, cons[0]);
            }
        }

        if(primaryContacts.size() > 0){
            update primaryContacts.values();
        }
    }
    
    // US_AU-CD-001.6 Track the updating history for FS fields
    public static void trackUpdatHistoryForFsInfo(Account updateAcc, Account oldAcc){
        if(updateAcc.FS_Opt_In_Email__c != oldAcc.FS_Opt_In_Email__c){
            updateAcc.FS_Email_Last_Modified_By__c = UserInfo.getName();
            updateAcc.FS_Email_Last_Modified_Date__c = System.now();
        }
        if(updateAcc.FS_Opt_In_Hardcopy__c != oldAcc.FS_Opt_In_Hardcopy__c){
            updateAcc.FS_Hardcopy_Last_Modified_By__c = UserInfo.getName();
            updateAcc.FS_Hardcopy_Last_Modified_Date__c = System.now();
        }
        
        if(updateAcc.FS_Opt_In_Phone__c != oldAcc.FS_Opt_In_Phone__c){
            updateAcc.FS_Phone_Last_Modified_By__c = UserInfo.getName();
            updateAcc.FS_Phone_Last_Modified_Date__c = System.now();
        }
        
        if(updateAcc.FS_Opt_In_SMS__c != oldAcc.FS_Opt_In_SMS__c){
            updateAcc.FS_SMS_Last_Modified_By__c = UserInfo.getName();
            updateAcc.FS_SMS_Last_Modified_Date__c = System.now();
        }
        if(updateAcc.Opt_In_Email__c != oldAcc.Opt_In_Email__c){
            updateAcc.Email_Last_Modified_By__c = UserInfo.getName();
            updateAcc.Email_Last_Modified_Date__c = System.now();
        }
        if(updateAcc.Opt_In_Hardcopy__c != oldAcc.Opt_In_Hardcopy__c){
            updateAcc.Hardcopy_Last_Modified_By__c = UserInfo.getName();
            updateAcc.Hardcopy_Last_Modified_Date__c = System.now();
        }
        
        if(updateAcc.Opt_In_Phone__c != oldAcc.Opt_In_Phone__c){
            updateAcc.Phone_Last_Modified_By__c = UserInfo.getName();
            updateAcc.Phone_Last_Modified_Date__c = System.now();
        }
        
        if(updateAcc.Opt_In_SMS__c != oldAcc.Opt_In_SMS__c){
            updateAcc.SMS_Last_Modified_By__c = UserInfo.getName();
            updateAcc.SMS_Last_Modified_Date__c = System.now();
        }
    }
    
    //Delete Dealer locators   US_AU-DD-004
    public static void deleteDealerLocators(Set<Id> dealerIds) {
    	
        try {
        	//   CR-000213 start
            List<Dealer_Locator__c> dealerLocators = [select Id from Dealer_Locator__c where Dealer_Name__c in :dealerIds];
            for (Dealer_Locator__c dl : dealerLocators){
                 dl.Inactive__c = true;
            }
            update dealerLocators;
            List<Contact> contacts = [select id from Contact where AccountId in :dealerIds];
            for (Contact con : contacts){
                 con.Inactive__c = true;
            }
            update contacts;
            //   CR-000213 end
        }
        catch(Exception ex) {
            trigger.new[0].addError('inactivate Dealer Locator Error, please contact administrator');
        }
    }
}