metadata-retriever/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CV_No_Brand_Purchases__c</fullName>
        <description>PC &amp; CV No. Brand Purchases: These fields display the amount of purchases for MB PC  or CV the customer has made during the time frame first purchase and today. (frequency of calculation needs to be defined)</description>
        <label>CV No. Brand Purchases</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CV_Status__c</fullName>
        <description>Needs to be coded:

Status a customer can have in regards to CV. 
Prospect - is interested in CV
Customer - does have at least one CV
Service Only - does have at least one After Sales Record</description>
        <label>CV Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CV_Tenure__c</fullName>
        <description>PC &amp; CV tenure: these fields display the endurance the customer stays with MB PC  or CV. Calculation is based on the first purchase date of MB PC  or CV (information available on the customer vehicle relationship) (frequency of calculation needs to be defined)</description>
        <label>CV Tenure</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PC_No_Brand_Purchases__c</fullName>
        <description>PC &amp; CV No. Brand Purchases: These fields display the amount of purchases for MB PC  or CV the customer has made during the time frame first purchase and today. (frequency of calculation needs to be defined)</description>
        <label>PC No. Brand Purchases</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <label>PC Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PC_Tenure__c</fullName>
        <description>PC &amp; CV tenure: these fields display the endurance the customer stays with MB PC  or CV. Calculation is based on the first purchase date of MB PC  or CV (information available on the customer vehicle relationship) (frequency of calculation needs to be defined)</description>
        <label>PC Tenure</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VAN_No_Brand_Purchases__c</fullName>
        <label>VAN No. Brand Purchases</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VAN_Status__c</fullName>
        <label>VAN Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VAN_Tenure__c</fullName>
        <label>VAN Tenure</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Customer_Vehicle_Relationship__c.object
<CustomObject>
    <description>Stores information on Vehicle Relationship</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>ID of related person</inlineHelpText>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Company, Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationship</relationshipLabel>
        <relationshipName>CustomerVehicleRelationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Stores information on Vehicle (cannot be created, but specific fields can be updated)</description>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <picklist>
            <picklistValues>
                <fullName>A-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All New A-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-Class Coupe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLA-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLC-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLK-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLS-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLS Shooting Brake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FIGHTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F SERIES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB 100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB 140</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ROSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLK-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLS AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLS-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart Forfour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart Fortwo cabrio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valente</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/classes/CustomerVehicleRelHelperTest.cls
/*
    Type:       Test class
    Purpose:    Test the CustomerDealerRelHelper class
    User Story: 
    ---------------------------------------------------------------
    History:

    1. Bai Bing created on 2013-08-20
*/
@isTest(seeAllData=true)
private class CustomerVehicleRelHelperTest {

    private static TestDataUtil testData = TestDataUtil.getInstance();
    private static Account customer1 = testData.standardPersonAccount;
    
    static testMethod void myUnitTest() {
        insert customer1;
        Vehicle__c car1 = new Vehicle__c(Name='xxxxxxxx01',Class__c='C-Class Sedan');
        Vehicle__c car2 = new Vehicle__c(Name='xxxxxxxx02',Class__c='CL-Class');
        Vehicle__c car3 = new Vehicle__c(Name='xxxxxxxx03',Class__c='Valente');
        Vehicle__c car4 = new Vehicle__c(Name='xxxxxxxx04',Class__c='Fighter');
        insert car1;
        Customer_Vehicle_Relationship__c cvr = new Customer_Vehicle_Relationship__c(Customer__c=customer1.id,Vehicle_ID__c=car1.id);
        insert cvr;
        
        customer1 = [select id, PC_Status__c, CV_Status__c,PC_Tenure__c,CV_Tenure__c, PC_No_Brand_Purchases__c,
                    CV_No_Brand_Purchases__c from Account where Id = :customer1.id];
        
        /*System.assertEquals(customer1.PC_Status__c,'Customer');
        System.assertEquals(customer1.PC_Tenure__c,0);
        System.assertEquals(customer1.PC_No_Brand_Purchases__c,1);*/

        insert car2;
        cvr = new Customer_Vehicle_Relationship__c(Customer__c=customer1.id,Vehicle_ID__c=car2.id);
        insert cvr;

        customer1 = [select id, PC_Status__c, CV_Status__c,PC_Tenure__c,CV_Tenure__c, PC_No_Brand_Purchases__c,
                    CV_No_Brand_Purchases__c from Account where Id = :customer1.id];
                            
        /*System.assertEquals(customer1.PC_Status__c,'Customer');
        System.assertEquals(customer1.PC_Tenure__c,0);
        System.assertEquals(customer1.PC_No_Brand_Purchases__c,2);*/

        insert car3;
        cvr = new Customer_Vehicle_Relationship__c(Customer__c=customer1.id,Vehicle_ID__c=car3.id);
        insert cvr;

        customer1 = [select id, VAN_Status__c,VAN_Tenure__c,
                    VAN_No_Brand_Purchases__c from Account where Id = :customer1.id];
                            
        /*System.assertEquals(customer1.VAN_Status__c,'Customer');
        System.assertEquals(customer1.VAN_Tenure__c,0);
        System.assertEquals(customer1.VAN_No_Brand_Purchases__c,1);*/
        

        cvr = new Customer_Vehicle_Relationship__c(Customer__c=customer1.id);
        
        try{
            insert cvr;
        }catch(DMLException e){
            //system.assertEquals('Please select the vehicle Id !',e.getDmlMessage(0));
        }
    }
}