metadata-retriever/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Only for person account. Look up to customer company as the contact.</description>
        <label>Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Company</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Copy_Postal_Address_2_Street_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Copy Postal Address To Street Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>Concatenated information - Display Name. The field &quot;Display Name&quot; shall display the correct salutation,  probably used to address the customer correctly, as per definition:
a) if the surname of Customer and Partner is equal then &lt;Title Customer&gt; and &lt;Title Partner&gt; &lt;Surname Customer&gt; (e.g. Mr and Ms Jones)
b) If the surname  is unequal the &lt;Title Customer&gt;  &lt;First Name Surname Customer&gt; and &lt;Title Partner&gt;  &lt;First Name Surname Partner&gt;  (e.g. Mr Mark Jones and Ms Amie Davison)
c.) if no partner information available &lt;Customer Title&gt; &lt; First Name&gt; &lt;Surname&gt;</description>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FS_Email_Last_Modified_By__c</fullName>
        <label>FS Email Last Modified By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FS_Email_Last_Modified_Date__c</fullName>
        <label>FS Email Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FS_Hardcopy_Last_Modified_By__c</fullName>
        <label>FS Mail Last Modified By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FS_Hardcopy_Last_Modified_Date__c</fullName>
        <label>FS Mail Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FS_Opt_In_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FS Opt In Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FS_Opt_In_Hardcopy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FS Opt In Mail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FS_Opt_In_Phone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FS Opt In Phone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FS_Opt_In_SMS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FS Opt In SMS/MMS/IM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FS_Phone_Last_Modified_By__c</fullName>
        <label>FS Phone Last Modified By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FS_Phone_Last_Modified_Date__c</fullName>
        <label>FS Phone Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FS_SMS_Last_Modified_By__c</fullName>
        <label>FS SMS/MMS/IM Last Modified By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FS_SMS_Last_Modified_Date__c</fullName>
        <label>FS SMS/MMS/IM Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opt_In_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PersonHasOptedInOfEmail, per default un checked</description>
        <label>Opt In Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opt_In_Hardcopy__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PersonHasOptedOutOfHardCopy</description>
        <label>Opt In Mail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opt_In_Phone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PersonHasOptedInOfPhone</description>
        <label>Opt In Phone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opt_In_SMS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PersonHasOptedInOfSMS</description>
        <label>Opt In SMS/MMS/IM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Surname__c</fullName>
        <label>Partner Surname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Title__c</fullName>
        <description>Partner Title - Should be the same values as used for the customer title</description>
        <label>Partner Title</label>
        <picklist>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mrs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Captain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chaplain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colonel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulate General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Countess</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estate of the Late</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Her Excellency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>His Excellency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Honourable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Justice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lady</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lieutenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lieutenant Colonel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lord</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Madam</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/classes/AccountHelperTest.cls
/*
    Type:       Account Controller Test
    Purpose:    Test the class
    User Story: 
    ---------------------------------------------------------------
    History:

    1. Bai Bing created on 2013-08-08
    2. Jusitn Yu updated on 2013-11-05
*/
@isTest
private class AccountHelperTest {

    private static TestDataUtil testData = TestDataUtil.getInstance();

    @isTest static void myUnitTest() {
        Account customer1 = testData.standardPersonAccount;
        insert customer1;

        customer1.Partner_Title__c = 'pTitle';
        customer1.Partner_Surname__c = 'pSurName';
        update customer1;
        //system.assertEquals('Professor FirstName LastName and pTitle pSurName', [select Display_Name__c from Account where id=:customer1.id].Display_Name__c);
        
        customer1.Partner_Surname__c = 'LastName';
        update customer1;
        //system.assertEquals('Professor and pTitle LastName', [select Display_Name__c from Account where id=:customer1.id].Display_Name__c);
        
        Account companyAcct = testData.standardCompanyAccount;
        insert companyAcct;
        Account customer2 = customer1.clone();
        customer2.FirstName = 'customer2';
        customer2.LastName = 'customer2';
        customer2.Copy_Postal_Address_2_Street_Address__c = true;
        insert customer2;
        
        customer1.Company__c = companyAcct.id;
        update customer1;
        //system.assertEquals(true,[select Primary__pc from Account where id=:customer1.id].Primary__pc);
        
        customer2.Company__c = companyAcct.Id;
        update customer2;
        //system.assertEquals(true,[select Primary__pc from Account where id=:customer2.id].Primary__pc);
        //system.assertEquals(false,[select Primary__pc from Account where id=:customer1.id].Primary__pc);
        
        delete customer2;
        //system.assertEquals(true,[select Primary__pc from Account where id=:customer1.id].Primary__pc);
    }
    
    @isTest static void testTrackUpdateHistory() {
        Account testAccount = testData.standardPersonAccount;
        insert testAccount;
        
        testAccount.FS_Opt_In_Email__c = true;
        testAccount.Opt_In_Email__c = true;
        update testAccount;
        testAccount = [select FS_Email_Last_Modified_By__c, FS_Email_Last_Modified_Date__c from Account where Id = :testAccount.Id];
        //System.assertEquals(testAccount.FS_Email_Last_Modified_By__c, UserInfo.getName());
        
        testAccount.FS_Opt_In_Hardcopy__c = true;
        testAccount.Opt_In_Hardcopy__c = true;
        update testAccount;
        testAccount = [select FS_Hardcopy_Last_Modified_By__c, FS_Hardcopy_Last_Modified_Date__c from Account where Id = :testAccount.Id];
        //System.assertEquals(testAccount.FS_Hardcopy_Last_Modified_By__c, UserInfo.getName());
        
        testAccount.FS_Opt_In_Phone__c = true;
        testAccount.Opt_In_Phone__c = true;
        update testAccount;
        testAccount = [select FS_Phone_Last_Modified_By__c, FS_Phone_Last_Modified_Date__c from Account where Id = :testAccount.Id];
        //System.assertEquals(testAccount.FS_Phone_Last_Modified_By__c, UserInfo.getName());

        testAccount.FS_Opt_In_SMS__c = true;
        testAccount.Opt_In_SMS__c = true;
        update testAccount;
        testAccount = [select FS_SMS_Last_Modified_By__c, FS_SMS_Last_Modified_Date__c from Account where Id = :testAccount.Id];
        //System.assertEquals(testAccount.FS_SMS_Last_Modified_By__c, UserInfo.getName());   
    } 
}