metadata-retriever/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CV_No_Brand_Purchases__c</fullName>
        <description>PC &amp; CV No. Brand Purchases: These fields display the amount of purchases for MB PC  or CV the customer has made during the time frame first purchase and today. (frequency of calculation needs to be defined)</description>
        <label>CV No. Brand Purchases</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CV_Status__c</fullName>
        <description>Needs to be coded:

Status a customer can have in regards to CV. 
Prospect - is interested in CV
Customer - does have at least one CV
Service Only - does have at least one After Sales Record</description>
        <label>CV Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CV_Tenure__c</fullName>
        <description>PC &amp; CV tenure: these fields display the endurance the customer stays with MB PC  or CV. Calculation is based on the first purchase date of MB PC  or CV (information available on the customer vehicle relationship) (frequency of calculation needs to be defined)</description>
        <label>CV Tenure</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PC_No_Brand_Purchases__c</fullName>
        <description>PC &amp; CV No. Brand Purchases: These fields display the amount of purchases for MB PC  or CV the customer has made during the time frame first purchase and today. (frequency of calculation needs to be defined)</description>
        <label>PC No. Brand Purchases</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <label>PC Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PC_Tenure__c</fullName>
        <description>PC &amp; CV tenure: these fields display the endurance the customer stays with MB PC  or CV. Calculation is based on the first purchase date of MB PC  or CV (information available on the customer vehicle relationship) (frequency of calculation needs to be defined)</description>
        <label>PC Tenure</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VAN_No_Brand_Purchases__c</fullName>
        <label>VAN No. Brand Purchases</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VAN_Status__c</fullName>
        <label>VAN Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VAN_Tenure__c</fullName>
        <label>VAN Tenure</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Customer_Vehicle_Relationship__c.object
<CustomObject>
    <description>Stores information on Vehicle Relationship</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>ID of related person</inlineHelpText>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Company, Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationship</relationshipLabel>
        <relationshipName>CustomerVehicleRelationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Date__c</fullName>
        <inlineHelpText>Purchase date of vehicle (information from leads, not from sales)</inlineHelpText>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Stores information on Vehicle (cannot be created, but specific fields can be updated)</description>
    <fields>
        <fullName>Vehicle_Group__c</fullName>
        <label>Vehicle Group</label>
        <picklist>
            <picklistValues>
                <fullName>VAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CV</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/classes/CustomerVehicleRelHelper.cls
/*
    Type:       Utility for Customer_Vehicle_Relationship__c
    Purpose:    1.when get a CustomerVehicle data , update tenure
    User Story: US_AU-CD-001
    Used By:    
    ---------------------------------------------------------------
    History:
    
    1. Bing Bai Created on 2013-08-05
*/
public with sharing class CustomerVehicleRelHelper {

    //US-CD-001
    //Get vehiches Vehicle_Group__c by vehicle id
    public static Map<id,Vehicle__c> getVehichles(set<Id> ids){
        return new Map<id,Vehicle__c>(
        [select id,
               Vehicle_Group__c
        from Vehicle__c 
        where Id in :ids]);
       
    }
    
    //get the lastest record
    public static Map<String,Date> getExsitedInfos(Set<Id> customerIds , String vehicleGroup){
        Map<String,Date>  recordsInfo = new Map <String,Date>();
        for (sObject obj:[select Customer__c, min(Purchase_Date__c) Purchase_Date__c from Customer_Vehicle_Relationship__c where Vehicle_ID__r.Vehicle_Group__c = :vehicleGroup and Customer__c in :customerIds group by Customer__c]){
            recordsInfo.put(String.valueOf(obj.get('Customer__c')),Date.valueOf(obj.get('Purchase_Date__c')));
        }
        
        return  recordsInfo;
    }
    
    private static Map<String, List<String>> colsMap = new Map<String,List<String>>
        {'PC'=> new List<String>{'PC_Status__c','PC_No_Brand_Purchases__c','PC_Tenure__c'},
         'CV'=> new List<String>{'CV_Status__c','CV_No_Brand_Purchases__c','CV_Tenure__c'},
         'VAN'=> new List<String>{'VAN_Status__c','VAN_No_Brand_Purchases__c','VAN_Tenure__c'}
        };
        
    //update PC CV VAN tenure
    private static Account updatePCCVField(Account userInfo ,String vehicleGroup, Map<String ,Map<String,Date>> preRecords){
        if(!String.isblank(vehicleGroup)){
            Map<String,Date> preRecord = preRecords.get(vehicleGroup);
            List<String> cols = colsMap.get(vehicleGroup);
            
            userInfo.put(cols[0], 'customer');
            integer numberofP = 1;
            if(userInfo.get(cols[1])!=null){
                numberofP = integer.valueOf(userInfo.get(cols[1]))+1;
            }
            userInfo.put(cols[1], Decimal.valueOf(numberofP));
            integer tenure = 0;
            if(preRecord.get(userInfo.id) != null){
                tenure = preRecord.get(userInfo.id).monthsBetween(Date.today())/12;
            }
            
            userInfo.put(cols[2] , Decimal.valueOf(tenure));
        }
        return userInfo;        
    }
        
    //US-CD-001 No.11
    //When PA gets a Customer-Vehicle-Relationship
    public static void updataWhenCreateCVR(Set<Id> vehicleIds, Set<Id> customerIds, List<Customer_Vehicle_Relationship__c> cvrs) {
        Map<id,Account> accounts = new Map<id,Account>();
        Map<String, Map<String,Date>> exsisedRecord = new Map<String, Map<String,Date>>();
        //get pc first date records
        Map<String,Date>  preRecordsPc = getExsitedInfos(customerIds,'PC');
        //get cv first date records 
        Map<String,Date>  preRecordsCv = getExsitedInfos(customerIds,'CV');
        //get cv first date records 
        Map<String,Date>  preRecordsVAN = getExsitedInfos(customerIds,'VAN');
        system.debug(customerIds);
        system.debug(preRecordsPc);    
        exsisedRecord.put('PC', preRecordsPc);
        exsisedRecord.put('CV', preRecordsCv);
        exsisedRecord.put('VAN', preRecordsVAN);
        
        Map<id,Account> accs = AccountHelper.getCustomerInfos(customerIds);
        Map<id,Vehicle__c> vehichles = getVehichles(vehicleIds);
        for(Customer_Vehicle_Relationship__c curCvr : cvrs){
            Account acc = new Account();
            if(accounts.containsKey(curCvr.Customer__c)){
                acc = accounts.get(curCvr.Customer__c);
            }else{
                acc = accs.get(curCvr.Customer__c);
            }
            acc = updatePCCVField(acc, vehichles.get(curCvr.Vehicle_ID__c).Vehicle_Group__c, exsisedRecord);
            
            accounts.put(acc.id,acc);
        }
        DBUtil.updateSobjects(accounts.values());
    }    
}