metadata-retriever/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CV_Status__c</fullName>
        <description>Needs to be coded:

Status a customer can have in regards to CV. 
Prospect - is interested in CV
Customer - does have at least one CV
Service Only - does have at least one After Sales Record</description>
        <label>CV Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Only for person account. Look up to customer company as the contact.</description>
        <label>Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Company</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fleet__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fleet</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <label>PC Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VAN_Status__c</fullName>
        <label>VAN Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <description>Stores information on companies</description>
        <label>Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Dealer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the dealer name who is involved in this contract</description>
        <label>Dealer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <filterItems>
                <field>Account.Dealer_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (Dealer Name)</relationshipLabel>
        <relationshipName>Contracts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fleet__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Fleet - indicates whether the related compay is a fleet customer or not</description>
        <inlineHelpText>Fleet - indicates whether the related compay is a fleet customer or not</inlineHelpText>
        <label>Fleet</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Signer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be populated in case the borrower is a company and the customer information has been delivered by CMS</description>
        <label>Signer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Signer Contracts</relationshipLabel>
        <relationshipName>SignerContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>VIN - Displays the VIN of the vehicle linked to the contract</description>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X150_Days_Before_EOC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>/*
Created By Polaris Yu 2013-8-22
Function: This field will be updated by workflow 150 days before the contract end date to trigger the auto creating leads function and sending email function
Used By: 
*/</description>
        <label>*150 Days Before EOC</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Fleet__c.object
<CustomObject>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Fleet</relationshipLabel>
        <relationshipName>Fleet</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fleet</label>
    <nameField>
        <label>Fleet Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Lead_Account__c.object
<CustomObject>
    <description>Stores information on leads</description>
    <fields>
        <fullName>Assigned_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <filterItems>
                <field>Account.Dealer_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Assigned Dealer)</relationshipLabel>
        <relationshipName>Leads_Account_Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Company, Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Contact)</relationshipLabel>
        <relationshipName>Leads_Account_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Existing_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRM1 Existing Contract No.</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Finance_Send_Email_Before_150_Days__c</fullName>
        <defaultValue>false</defaultValue>
        <description>/*
Created By PolarisYu 2013-9-2
Function: To mark those leads auto created for EOC, will be checked when the leads created
Used By: LeadHelper
*/</description>
        <label>*Is Finance Send Email Before 150 Days</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <picklist>
            <picklistValues>
                <fullName>Web Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbound Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End of Contract</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Enquiry</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Attempt Made</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Actioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Credit Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote Provided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offer Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refer to Head Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Application Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documents Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financials Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Settlement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold Vehicle and Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Policy Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Settled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Nature_of_Request__c</fullName>
        <label>Nature of Request</label>
        <picklist>
            <picklistValues>
                <fullName>Brochure Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End of Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Payout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Key 2 Key</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Booking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Stores information on Vehicle (cannot be created, but specific fields can be updated)</description>
    <fields>
        <fullName>Vehicle_Group__c</fullName>
        <label>Vehicle Group</label>
        <picklist>
            <picklistValues>
                <fullName>VAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CV</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/classes/ContractHelper.cls
/*
    Type:       Utility for Contract
    Purpose:    for user story process unit 
    User Story: US_AU-CD-001, US_AU-CD-002
    Used By:    TriggerContractAfterInsertOrUpdate
    ---------------------------------------------------------------
    History:
        1. Bing Bai Created on 2013-08-05
        2. Justin Yu Updated on 2013-08-22
        3. Polaris Yu (BreakingPoint) Updated on 2013-8-23
        4. Polaris Yu (BreakingPoint) Updated on 2013-10-22
        5. Barney Lai Updated on 2014-03-13
*/
public with sharing class ContractHelper {

    //US-CD-001
    //Get vehiches Vehicle_Group__c by vehicle id
    public static Map<id,Vehicle__c> getVehichles(set<Id> ids){
        return new Map<id,Vehicle__c>(
        [select id,
               Vehicle_Group__c
        from Vehicle__c 
        where Id in :ids]);
    }
       
    //US-CD-001 No.11
    //When PA gets a Customer_Contract_Relationship__c
    public static void updataWhenCreateCCR(Set<Id> vehicleIds ,Set<Id> customerIds, List<Contract> cvrs){
        // Modified by Polaris Yu 2013-10-22, changed 'List<Account>' to 'Set<Account>'
        List<Account> accounts = new List<Account>();

        Map<id,Account> accs = AccountHelper.getCustomerInfos(customerIds);
        Map<id,Account> accountsForUpdate = new Map<id,Account>();
        Map<id,Vehicle__c> vehichles = getVehichles(vehicleIds);
        for(Contract curCcr: cvrs){
            if(!String.isblank(curCcr.AccountId)){
                Account acc = accs.get(curCcr.AccountId);
                if(vehichles.get(curCcr.Vehicle__c) != null){
                    if (vehichles.get(curCcr.Vehicle__c).Vehicle_Group__c == 'PC' ){
                        if(acc.PC_Status__c == 'Customer'){
                           continue;
                        }else{
                           acc.PC_Status__c = 'Customer';
                        }
                    }
                    if (vehichles.get(curCcr.Vehicle__c).Vehicle_Group__c == 'CV'){
                        if(acc.CV_Status__c == 'Customer'){
                           continue;
                        }else{
                           acc.CV_Status__c = 'Customer';
                        }
                    }
                    if (vehichles.get(curCcr.Vehicle__c).Vehicle_Group__c == 'Van'){
                        if(acc.VAN_Status__c == 'Customer'){
                           continue;
                        }else{
                           acc.VAN_Status__c = 'Customer';
                        }
                    }
                }
                accountsForUpdate.put(acc.Id, acc);
            }
        }
        
        DBUtil.updateSobjects(accountsForUpdate.values());
        // End of Added Part, Polaris Yu 2013-10-22
    }    
    
    // For US-CD-019 NO.2
    public static void createCompanyIndividualRelationship(Set<String> contractIds){
        List<Account> personAccounts = new List<Account>();
        //Barney lai 2014-3-13 start
        Map<Id, Account> idPersonAccounts = new Map<Id, Account>();
        //Barney lai 2014-3-13 end
        for(Contract contract : [select AccountId, Signer__c, Account.RecordType.Name, Signer__r.Company__c
                                 from Contract where Id in :contractIds]){
            if(contract.Account.RecordType.Name == 'Company' && contract.Signer__c != null){
                contract.Signer__r.Company__c = contract.AccountId;
                //Barney lai 2014-3-13 start
                idPersonAccounts.put(contract.Signer__r.id, contract.Signer__r);
                //Barney lai 2014-3-13 end
            }
        }
        //Barney lai 2014-3-13 start
        personAccounts = idPersonAccounts.values();
        //Barney lai 2014-3-13 end
        update personAccounts;
    }

    // Auto Create Leads
    // Added by Polaris Yu 2013-8-23; For User Story: 
    //    US_AU-Lead-011, US_AU-Lead-012
    public static void autoCreateLeads(Map<Id, Contract> newMap
        , Map<Id, Contract> oldMap){
        // Select the contracts that the '*150 Days Before EOC'
        //    field of which are updated to TRUE
        List<Contract> finCntrctList = new List<Contract>();
        List<Contract> fltCntrctList = new List<Contract>();
        for(Id curCntrctId : newMap.keySet()){
            if((oldMap.get(curCntrctId).X150_Days_Before_EOC__c
                != newMap.get(curCntrctId).X150_Days_Before_EOC__c)
                && newMap.get(curCntrctId).X150_Days_Before_EOC__c == TRUE){
                if(newMap.get(curCntrctId).Fleet__c == TRUE){
                    fltCntrctList.add(newMap.get(curCntrctId));
                }
                else{
                    finCntrctList.add(newMap.get(curCntrctId));
                }
            }
        }

        List<Lead_Account__c> newLeadList = new List<Lead_Account__c>();
        // Create finance leads based on the non-fleet contracts
        if(finCntrctList.size() > 0){
            // Get the finance lead record type information
            RecordType financeLdRT = [SELECT Id, Name FROM RecordType
                                      WHERE Name = 'Finance Lead'];
            if(financeLdRT != null){
                for(Contract curCntrct : finCntrctList){
                    Lead_Account__c newLead = new Lead_Account__c();
                    newLead.RecordTypeId = financeLdRT.Id;
                    newLead.Existing_Contract__c = curCntrct.Id;
                    newLead.Nature_of_Request__c = 'End of Contract';
                    newLead.OwnerId = curCntrct.OwnerId;
                    newLead.Lead_Status__c = 'New Enquiry';
                    newLead.Lead_Source__c = 'End of Contract';
                    newLead.Contact__c = curCntrct.AccountId;
                    newLead.Assigned_Dealer__c = curCntrct.Dealer_Name__c;
                    newLead.Is_Finance_Send_Email_Before_150_Days__c = true;
                    newLeadList.add(newLead);
                }
            }
        }

        // Create fleet leads based on the fleet contracts
        if(fltCntrctList.size() > 0){
            // Get the fleet lead record type information
            RecordType fleetLdRT = [SELECT Id, Name FROM RecordType
                                    WHERE Name = 'Fleet Lead'];
            if(fleetLdRT != null){
                for(Contract curCntrct : fltCntrctList){
                    Lead_Account__c newLead = new Lead_Account__c();
                    newLead.RecordTypeId = fleetLdRT.Id;
                    newLead.Existing_Contract__c = curCntrct.Id;
                    newLead.Nature_of_Request__c = 'End of Contract';
                    newLead.OwnerId = curCntrct.OwnerId;
                    newLead.Lead_Status__c = 'New Enquiry';
                    newLead.Lead_Source__c = 'End of Contract';
                    newLead.Company_Account__c = curCntrct.AccountId;
                    newLead.Assigned_Dealer__c = curCntrct.Dealer_Name__c;
                    newLead.Business_Unit__c = 'Fleet';
                    newLead.Sub_BusinessUnit__c = 'Finance';
                    newLead.Is_Fleet_Send_Email_Before_150_Days__c = true;
                    newLeadList.add(newLead);
                }
            }
        }

        // Insert the new leads into the system
        if(newLeadList.size() > 0){
            try{
                insert newLeadList;
                
                // Send email notifications to corresponding recipients
                //US_AU_CR-000171 Modified by Bing Start
                //LeadHelper.sendEOCEmailNotifications(newLeadList);
                LeadHelper.send171Email(newLeadList);
                //US_AU_CR-000171 Modified by Bing End
            }
            catch(DMLException e){
                Trigger.new[0].addError('Error: ' + e);
            }
        }
    }
    // End of added part, Polaris Yu 2013-8-23
}