metadata-retriever/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CV_Status__c</fullName>
        <description>Needs to be coded:

Status a customer can have in regards to CV. 
Prospect - is interested in CV
Customer - does have at least one CV
Service Only - does have at least one After Sales Record</description>
        <label>CV Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PC_Status__c</fullName>
        <label>PC Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VAN_Status__c</fullName>
        <label>VAN Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>VIN - Displays the VIN of the vehicle linked to the contract</description>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Customer_Vehicle_Relationship__c.object
<CustomObject>
    <description>Stores information on Vehicle Relationship</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>ID of related person</inlineHelpText>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Company, Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationship</relationshipLabel>
        <relationshipName>CustomerVehicleRelationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Stores information on Vehicle (cannot be created, but specific fields can be updated)</description>
    <fields>
        <fullName>Vehicle_Group__c</fullName>
        <label>Vehicle Group</label>
        <picklist>
            <picklistValues>
                <fullName>VAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CV</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/classes/AfterSalesHelper.cls
/*
    Type:       Aftersales util
    Purpose:    1.update pc cv van status when status is porspect or null
                
    User Story: US-CD-001
    Used By:    
    ---------------------------------------------------------------
    History:
    
*/
public with sharing class AfterSalesHelper {
    
    private static Map<String,String> updateFields = new Map<String,String>{
        'PC'=>'PC_Status__c',
        'CV'=>'CV_Status__c',
        'VAN'=>'VAN_Status__c'
    };
    
    //US_AU-CD-001 update pc cv van status when status is porspect or null
    public static void updateAccountStatus(Set<Id> ids){
    
        //get vechile info 
        Map<Id,Vehicle__c> vehicles = new Map<Id,Vehicle__c>
        ([select id, Vehicle_Group__c from Vehicle__c where id in: ids]);
        
        Map<String,Map<String,Integer>> cvrInfos = new Map<String,Map<String,Integer>>();
        Map<String,Map<String,Integer>> contractInfos = new Map<String,Map<String,Integer>>();
        Map<id,id> customers = new Map<id,id>(); 

        for(Customer_Vehicle_Relationship__c cvr: [select Vehicle_ID__c, Customer__c from Customer_Vehicle_Relationship__c 
         where Vehicle_ID__c in :ids]){
            if(!customers.containsKey(cvr.Customer__c)){
                customers.put(cvr.Customer__c,cvr.Vehicle_ID__c);
            }
         }

        for(Sobject rel : 
        [select count(Id) ammount, Vehicle_ID__r.Vehicle_Group__c, Customer__c from Customer_Vehicle_Relationship__c 
         where Customer__c in :customers.keyset()
         group by Customer__c,Vehicle_ID__r.Vehicle_Group__c]){
              integer ammount = Integer.valueOf(rel.get('ammount'));
              String vehicleGroup = String.valueOf(rel.get('Vehicle_Group__c'));
              String customerId = String.valueOf(rel.get('Customer__c'));
             if(cvrInfos.containsKey(customerId)){
                 cvrInfos.get(customerId).put(vehicleGroup,ammount);
             }else{
                cvrInfos.put(customerId, new Map<String,Integer>{vehicleGroup=>ammount});
             }
         }
        
        for(Sobject acontract: [select count(id) ammount, 
                                       Vehicle__r.Vehicle_Group__c,
                                       AccountId 
                                from contract 
                                where AccountId in : customers.keyset() 
                                group by AccountId,Vehicle__r.Vehicle_Group__c ]){
             integer ammount = Integer.valueOf(acontract.get('ammount'));
             String vehicleGroup = String.valueOf(acontract.get('Vehicle_Group__c'));
             String customerId = String.valueOf(acontract.get('AccountId'));
             if(contractInfos.containsKey(customerId)){
                contractInfos.get(customerId).put(vehicleGroup,ammount);
             }else{
                contractInfos.put(customerId, new Map<String,Integer>{vehicleGroup=>ammount});
             }
        }
       
        List<Account> forUpdate = new List<Account>();
        for(Account customer: [select id, PC_Status__c, CV_Status__c, VAN_Status__c from Account where id in:customers.keyset()]){
            Vehicle__c vehicleInfo = vehicles.get(customers.get(customer.id));
            boolean hasCvrRec = false;
            boolean hasContractRec = false;
            if(cvrInfos.containsKey(customer.id) ){
                if(cvrInfos.get(customer.id).containskey(vehicleInfo.Vehicle_Group__c)){
                    hasCvrRec = true;
                }
            }
            if(contractInfos.containsKey(customer.id) ){
                if(contractInfos.get(customer.id).containskey(vehicleInfo.Vehicle_Group__c)){
                    hasContractRec = true;
                }
            }

            if(!hasCvrRec && !hasContractRec){
               if (!String.isblank(vehicleInfo.Vehicle_Group__c) && updateFields.containsKey(vehicleInfo.Vehicle_Group__c)){
                   String fieldName = updateFields.get(vehicleInfo.Vehicle_Group__c);
                   customer.put(fieldName,'Service Only');
                   forUpdate.add(customer);
               }
            }
        }
        
        DButil.updateSobjects(forUpdate);
    }
}