metadata-retriever/metadata/objects/CMS_Contracts_Relation__c.object
<CustomObject>
    <fields>
        <fullName>CRM1_Case_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRM1 Case No.</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CMS Contracts Relations</relationshipLabel>
        <relationshipName>CMS_Contracts_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CMS Contracts Relation</label>
    <nameField>
        <label>CMS Contracts Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CMS Contracts Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata-retriever/metadata/classes/NewCMSContractsRelationController.cls
/*
    Purpose:    Return to Case detail when save the new CMS record
    User Story: quick wins FOS Complaint

    Used By:    
    ---------------------------------------------------------------
    History:

    2015-02-26 Sinow Created
*/
public class NewCMSContractsRelationController {
    
    public CMS_Contracts_Relation__c CMSContractsRelationInfo {get; set;}
    
    public NewCMSContractsRelationController(ApexPages.StandardController stdController) {
        
        CMSContractsRelationInfo = (CMS_Contracts_Relation__c)stdController.getRecord();
        CMSContractsRelationInfo.OwnerId = UserInfo.getUserId();
    }
    
    public pageReference saveCMS() {
        try {
            insert CMSContractsRelationInfo;
        }
        catch(exception ex) {
            return null;
        }
        return new PageReference('/' + CMSContractsRelationInfo.CRM1_Case_No__c);
    }
    
    public pageReference cancelCMS() {
        return new PageReference('/' + CMSContractsRelationInfo.CRM1_Case_No__c);
    }
}