metadata-retriever/metadata/objects/CMS_Contracts_Relation__c.object
<CustomObject>
    <fields>
        <fullName>CRM1_Case_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRM1 Case No.</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CMS Contracts Relations</relationshipLabel>
        <relationshipName>CMS_Contracts_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CMS Contracts Relation</label>
    <nameField>
        <label>CMS Contracts Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CMS Contracts Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contract_Id__c</fullName>
        <description>Unique Idenetifier from CMS</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique Idenetifier from CMS</inlineHelpText>
        <label>CMS Contract No.</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/classes/NewCMSContractsRelationControllerTest.cls
/*
    Type:       test class
    Purpose:    NewCMSContractsRelationController test class
    User Story: quick wins FOS Complaint

    Used By:    NewCMSContractsRelationController 
    ---------------------------------------------------------------
    History:

    2015-02-27 Sinow Created
*/
@isTest
public class NewCMSContractsRelationControllerTest {

    private static Id FOSId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('FOS Complaint').getRecordTypeId();
    private static TestDataUtil testData = TestDataUtil.getInstance();
       
    public static testMethod void testNewCMSContractsRelationController() {
        
        Account customer = testData.standardPersonAccount;
        insert customer;
        
        Contract contr = new Contract();
        contr.Contract_Id__c = 'acme1234';
        contr.AccountId = customer.Id;
        insert contr;
        
        Case c = new Case();
        c.RecordTypeId = FOSId;
        c.Subject = 'acme';
        insert c;
        
        CMS_Contracts_Relation__c cms = new CMS_Contracts_Relation__c();
        cms.CRM1_Case_No__c = c.Id;
        
        ApexPages.standardController controller = new ApexPages.standardController(cms);
        NewCMSContractsRelationController newCMS = new NewCMSContractsRelationController(controller);
        newCMS.CMSContractsRelationInfo.Name = 'acme1234';
        newCMS.saveCMS();
        newCMS.cancelCMS();
    }
}