metadata-retriever/metadata/objects/Customer_Vehicle_Relationship__c.object
<CustomObject>
    <description>Stores information on Vehicle Relationship</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>ID of related person</inlineHelpText>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Company, Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationship</relationshipLabel>
        <relationshipName>CustomerVehicleRelationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Stores information on Vehicle (cannot be created, but specific fields can be updated)</description>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <picklist>
            <picklistValues>
                <fullName>A-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All New A-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-Class Coupe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLA-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLC-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLK-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLS-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLS Shooting Brake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FIGHTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F SERIES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB 100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB 140</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ROSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLK-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLS AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLS-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart Forfour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart Fortwo cabrio</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/classes/ReportUserControllerTest.cls
/*
    Type:       ReportUserController Test
    Purpose:    Test the class
    User Story: 
    ---------------------------------------------------------------
    History:

    1. Shuang Li created on 2013-09-13

*/
@isTest
public class ReportUserControllerTest {

    @isTest
    public static void testReportUserController(){
        
        UserRole r = new UserRole(name = 'TEST ROLE');
        Database.insert(r);
        
        Profile pro = [select Id from Profile where Name = 'System Administrator'];
        
        User userWithRoleAdd = new User(alias = 'hasrole', email='userwithrole@roletest1.com', userroleid = r.id,
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
        localesidkey='en_US', profileid = Pro.Id,
        timezonesidkey='America/Los_Angeles', username='userwithroleAdd@testorg.com');
        
        User userWithRoleMod = new User(alias = 'hasrole', email='userwithrole@roletest1.com', userroleid = r.id,
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
        localesidkey='en_US', profileid = Pro.Id,
        timezonesidkey='America/Los_Angeles', username='userwithroleMod@testorg.com');
        insert userWithRoleAdd;
        insert userWithRoleMod;
        TestDataUtil testData = TestDataUtil.getInstance();
    	Account customer1 = testData.standardPersonAccount;
        Vehicle__c car1 = new Vehicle__c(Name='xxxxxxxx01', Class__c='C-Class Sedan');
        Vehicle__c car2 = new Vehicle__c(Name='xxxxxxxx02', Class__c='CL-Class');
        Task task1 = new Task(ActivityDate = Date.today(), CallDisposition = 'Contact left a message1', CallType = 'Inbound', Description = 'aa', Status = 'Completed', Subject = 'Phone Message from ', Type = 'Call');
        Task task2 = new Task(ActivityDate = Date.today(), CallDisposition = 'Contact left a message2', CallType = 'Inbound', Description = 'aab', Status = 'Completed', Subject = 'Phone Message from1 ', Type = 'Call');

        System.runAs(userWithRoleAdd) {
            insert task1;
            insert task2;
            insert customer1;
            insert car1;
            insert car2;
            Customer_Vehicle_Relationship__c cvr1 = new Customer_Vehicle_Relationship__c(Customer__c=customer1.id,Vehicle_ID__c=car1.id);
            Customer_Vehicle_Relationship__c cvr2 = new Customer_Vehicle_Relationship__c(Customer__c=customer1.id,Vehicle_ID__c=car2.id);
            insert cvr1;
            insert cvr2;
        }
        System.runAs(userWithRoleMod) {
            update customer1;
            Customer_Vehicle_Relationship__c cvr3 = new Customer_Vehicle_Relationship__c(Customer__c=customer1.id,Vehicle_ID__c=car1.id);
            Customer_Vehicle_Relationship__c cvr4 = new Customer_Vehicle_Relationship__c(Customer__c=customer1.id,Vehicle_ID__c=car2.id);
            insert cvr3;
            insert cvr4;
            update cvr3;
            update task2;
        }
        
        
        ReportUserController controller = new ReportUserController();
        controller.getTheResults();
        for ( integer i=0;i< controller.theResults.size();i++){   
            if(userWithRoleAdd.Id == controller.theResults.get(i).UserId){
               System.assertEquals(1, controller.theResults.get(i).totalAccountAdd);
               System.assertEquals(0, controller.theResults.get(i).totalAccountMod);
               System.assertEquals(2, controller.theResults.get(i).totalTasksAdd);
               System.assertEquals(1, controller.theResults.get(i).totalTasksMod);
               System.assertEquals(2, controller.theResults.get(i).totalVehicleAdd);
               System.assertEquals(2, controller.theResults.get(i).totalVehicleMod);
            }else if(userWithRoleMod.Id == controller.theResults.get(i).UserId){
               System.assertEquals(0, controller.theResults.get(i).totalAccountAdd);
               System.assertEquals(1, controller.theResults.get(i).totalAccountMod);
               System.assertEquals(0, controller.theResults.get(i).totalTasksAdd);
               System.assertEquals(1, controller.theResults.get(i).totalTasksMod);
               System.assertEquals(2, controller.theResults.get(i).totalVehicleAdd);
               System.assertEquals(2, controller.theResults.get(i).totalVehicleMod);
            
            }          
        }
    }
}