metadata-retriever/metadata/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-retriever/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Stores information on Vehicle (cannot be created, but specific fields can be updated)</description>
    <fields>
        <fullName>CROUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CROUser</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 OR 2) AND 3</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>Customer Retention Office</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>Remarketing Team Lead</value>
            </filterItems>
            <filterItems>
                <field>User.Active_Inactive_Flag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-retriever/metadata/classes/TaskMassChangeOwner.cls
/*
    Type:       Controller for TaskMassChangeOwener Visualforce page 
    Purpose:    Mass reassign tasks 
    User Story: CR-000185
    Used By:    TaskMassChangeOwener.page
    ---------------------------------------------------------------
    History:
    
    1. Barney lai Created on 2014-02-28
*/

public with sharing class TaskMassChangeOwner {
    public Vehicle__c task{set;get;}    
    private String [] arrObjIds;    
    
    public TaskMassChangeOwner(){        
        //Initalize the variables   
             
        task = new Vehicle__c();        
        Map<String, String> params = ApexPages.currentPage().getParameters();        
        String strObjIds = params.get('objIds');        
        arrObjIds = strObjIds.split(',');                  
    }            
        
    public void assignToOwnerClick(){    
        if(task.CROUser__c == null){            
            Apexpages.addMessage(new Apexpages.Message(ApexPages.severity.ERROR,'New Owner Cannot be null.'));            
            return;        
        }
        List<Task> tasks = [Select Id, OwnerId From Task Where Id=:arrObjIds];        
        for(Task t : tasks){            
            t.OwnerId = task.CROUser__c;       
        }                
        if(tasks.size()>0){                        
            update tasks;         
        }    
    }
}